IDS = {
    0x00:"Capsule",
    0x01:"Box",
    0x02:"Barrel",
    0x03:"Egg",
    0x04:"Party Ball",
    0x05:"Barrel Cannon",
    0x06:"Bob-omb",
    0x07:"Mr. Saturn",
    0x08:"Heart Container",
    0x09:"Maxim Tomato",
    0x0A:"Starman",
    0x0B:"Home Run Bat",
    0x0C:"Beam Sword",
    0x0D:"Parasol",
    0x0E:"Green Shell",
    0x0F:"Red Shell ",
    0x10:"Ray Gun",
    0x11:"Freezie",
    0x12:"Food",
    0x13:"Motion Sensor Bomb",
    0x14:"Flipper",
    0x15:"Super Scope",
    0x16:"Star Rod",
    0x17:"Lip's Stick",
    0x18:"Fan",
    0x19:"Fire Flower",
    0x1A:"Super Mushroom",
    0x1B:"Poison Mushroom",
    0x1C:"Hammer",
    0x1D:"Warp Star",
    0x1E:"Screw Attack",
    0x1F:"Bunny Hood",
    0x20:"Metal Box",
    0x21:"Cloaking Device",
    0x22:"Pokeball",
    0x23:"Ray Gun projectile",
    0x24:"Star Rod's star",
    0x25:"Lip Stick's dust",
    0x26:"Super Scope's projectile",
    0x27:"???",
    0x28:"Hammer Head",
    0x29:"???",
    0x2A:"Yoshi's Egg from Event 13",

    #ENEMIES
    0x2B:"Goomba",
    0x2C:"Redead",
    0x2D:"Octorok",
    0x2E:"???",
    0x2F:"Octorok's projectile",

    #CHARACTER PROJECTILES - character associated with it must be in the match
    0x30:"Mario's Fireball",
    0x31:"Dr. Mario's Capsule",
    0x32:"Kirby's Cutter",
    0x33:"Kirby's Hammer",
    0x34:"???",
    0x35:"???",
    0x36:"Fox's Laser",
    0x37:"Falco's Laser",
    0x38:"Fox's Side-B Shadow",
    0x39:"Falco's Side-B Shadow",
    0x3A:"Link's Bomb",
    0x3B:"Young Link's Bomb",
    0x3C:"Link's Boomerang",
    0x3D:"Young Link's Boomerang",
    0x3E:"Link's Hookshot",
    0x3F:"Young Link's Hookshot",
    0x40:"Link's Arrow",
    0x41:"Young Link's Arrow",
    0x42:"PK Fire",
    0x43:"PK Flash",
    0x44:"PK Flash",
    0x45:"PK Thunder",
    0x46:"PK Thunder",
    0x47:"PK Thunder",
    0x48:"PK Thunder",
    0x49:"PK Thunder",
    0x4A:"Fox's Blaster",
    0x4B:"Falco's Blaster",
    0x4C:"Link's Arrow",
    0x4D:"Young Link's Arrow",
    0x4E:"PK Flash Explosion",
    0x4F:"Sheik's Needle",
    0x50:"Sheik's Needle",
    0x51:"Pikachu's Thunder",
    0x52:"Pichu's Thunder",
    0x53:"Mario's Cape",
    0x54:"Dr. Mario's Cape",
    0x55:"Sheik's Smoke",
    0x56:"Yoshi's Egg",
    0x57:"???",
    0x58:"Yoshi's Star",
    0x59:"Pikachu's Thunder",
    0x5A:"Pikachu's Thunder",
    0x5B:"Pichu's Thunder",
    0x5C:"Pichu's Thunder",
    0x5D:"Samus' Bomb",
    0x5E:"Samus' Chargeshot",
    0x5F:"Samus' Missle",
    0x60:"Samus' Grapple Beam",
    0x61:"Sheik's Chain",
    0x62:"???",
    0x63:"Peach's Turnips",
    0x64:"Bowser & Giga Bowser's fire",
    0x65:"Ness' Bat",
    0x66:"Ness' Yoyo",
    0x67:"Peach's Parasol",
    0x68:"Toad",
    0x69:"Luigi's Fire",
    0x6A:"Ice Climbers' Ice",
    0x6B:"Ice Climbers' Blizzard",
    0x6C:"Zelda's Fire",
    0x6D:"Zelda's Fire Explosion",
    0x6E:"???",
    0x6F:"Toad's Spore",
    0x70:"Mewtwo's Shadowball",
    0x71:"Ice Climbers' Up-B",
    0x72:"Pesticide",
    0x73:"Game & Watch's Manhole",
    0x74:"Game & Watch's Fire",
    0x75:"Game & Watch's Parachute",
    0x76:"Turtle",
    0x77:"Sperky",
    0x78:"Game & Watch's Judge",
    0x79:"???",
    0x7A:"Game & Watch's Sausage",
    0x7B:"Young Link's Milk",
    0x7C:"???",
    0x7D:"Master Hand's Lasers",
    0x7E:"Master Hand's Bullet",
    0x7F:"Crazy Hand's Lasers (Unused)",
    0x80:"Crazy Hand's Bullet (Unused)",
    0x81:"Crazy Hand's Bomb",
    0x82:"Mario's Fireball (Kirby)",
    0x83:"Dr. Mario's Capsule (Kirby)",
    0x84:"Luigi's Fireball (Kirby)",
    0x85:"Ice Climbers' Ice (Kirby)",
    0x86:"Peach's Toad (Kirby)",
    0x87:"Toad's Spore (Kirby)",
    0x88:"Fox's Laser (Kirby)",
    0x89:"Falco's Laser (Kirby)",
    0x8A:"Fox's Laser (Kirby)",
    0x8B:"Falco's Laser (Kirby)",
    0x8C:"Link's Arrow (Kirby)",
    0x8D:"Young Link's Arrow (Kirby)",
    0x8E:"Link's Arrow (Kirby)",
    0x8F:"Young Link's Arrow (Kirby)",
    0x90:"Mewtwo's Shadowball (Kirby)",
    0x91:"PK Flash (Kirby)",
    0x92:"PK Flash Explosion (Kirby)",
    0x93:"Pikachu's Thunder (Kirby)",
    0x94:"Pikachu's Thunder (Kirby)",
    0x95:"Pichu's Thunder (Kirby)",
    0x96:"Pichu's Thunder (Kirby)",
    0x97:"Samus' Chargeshot (Kirby)",
    0x98:"Sheik's Needle (Kirby)",
    0x99:"Sheik's Needle (Kirby)",
    0x9A:"Bowser's Flame (Kirby)",
    0x9B:"Game & Watch's Sausage (Kirby)",
    0x9C:"???",
    0x9D:"???",
    0x9E:"???",
    0x9F:"???",
    0xA0:"???",

    #POKEMON
    0xA1:"Goldeen",
    0xA2:"Chicorita",
    0xA3:"Snorlax",
    0xA4:"Blastoise",
    0xA5:"Weezing",
    0xA6:"Charizard",
    0xA7:"Moltres",
    0xA8:"Zapdos",
    0xA9:"Articuno",
    0xAA:"Wobbuffet",
    0xAB:"Scizor",
    0xAC:"Unown",
    0xAD:"Entei",
    0xAE:"Raikou",
    0xAF:"Suicine",
    0xB0:"Bellossom",
    0xB1:"Electrode",
    0xB2:"Lugia",
    0xB3:"Ho-oh",
    0xB4:"Ditto (Unused)",
    0xB5:"Clefairy",
    0xB6:"Togepi",
    0xB7:"Mew",
    0xB8:"Celebi",
    0xB9:"Staryu",
    0xBA:"Chansey",
    0xBB:"Porygon",
    0xBC:"Cyndaquill",
    0xBD:"Marill",
    0xBE:"Venusaur",
    0xBF:"Chicorita's Leaf",
    0xC0:"Blastoise's Water",
    0xC1:"Weezing's Gas",
    0xC2:"Weezing's Gas",
    0xC3:"Charizard's Fire",
    0xC4:"Charizard's Fire",
    0xC5:"Charizard's Fire",
    0xC6:"Charizard's Fire",
    0xC7:"Mini-Unowns",
    0xC8:"Lugia's Aeroblast",
    0xC9:"Lugia's Aeroblast",
    0xCA:"Lugia's Aeroblast",
    0xCB:"Ho-oh's Flame",
    0xCC:"Staryu's Star",
    0xCD:"Egg",
    0xCE:"Cyndaquill's Fire",
    0xCF:"???",
    0xD0:"???",

    #STAGE SPECIFIC - must be playing on the stage these appear in
    0xD1:"Target",
    0xD2:"Shy Guy",
    0xD3:"Koopa Troopa",
    0xD4:"Paratroopa",
    0xD5:"Like Like",
    0xD6:"???",
    0xD7:"???",
    0xD8:"???",
    0xD9:"Polar Bear",
    0xDA:"Klap Trap",
    0xDB:"Green Shell",
    0xDC:"Red Shell",
    0xDD:"Tingle",
    0xDE:"???",
    0xDF:"???",
    0xE0:"???",
    0xE1:"Green Greens Apple",
    0xE2:"Green Greens Apple",
    0xE3:"???",
    0xE4:"???",
    0xE5:"???",
    0xE6:"Flat Zone Tool",
    0xE7:"???",
    0xE8:"???",
    0xE9:"Birdo",
    0xEA:"Arwing's Laser",
    0xEB:"Great Fox's Laser",
    0xEC:"Birdo's Egg"
}

num = 51
string = ""
while num < 161:
    string += "$" + str(num) + " "
    num += 1
print(string)