from utility import bidict, get_value, set_value

AURAS = bidict({    0x0000: "Nothing",
                    0x0004: "Nothing", 
                    0x0008: "White Flash (Continuous)", 
                    0x000C: "Yellow Flash (Continuous)", 
                    0x0010: "White (Short)", 
                    0x0014: "Flashing White", 
                    0x0018: "Flashing Black",
                    0x001C: "Lens Flare", 
                    0x0020: "Healing Effect", 
                    0x0024: "Slow White Flashing", 
                    0x0028: "White Fade", 
                    0x002C: "Fire (Shortest)", 
                    0x0030: "Fire (Shorter)", 
                    0x0034: "Fire (Longer)", 
                    0x0038: "Fire (Longest)", 
                    0x003C: "Electric (Shortest)", 
                    0x0040: "Electric (Shorter)", 
                    0x0044: "Electric (Longer)", 
                    0x0048: "Electric (Longest)", 
                    0x004C: "Flashing Black & Electric", 
                    0x0050: "Flashing Black & Electric", 
                    0x0054: "Flashing Black & Electric", 
                    0x0058: "Flashing Black & Electric", 
                    0x005C: "Flashing Black & Electric", 
                    0x0060: "Flashing Black & Electric", 
                    0x0064: "Flashing Black & Electric", 
                    0x0068: "Flashing Black & Electric", 
                    0x006C: "Flashing Black & Electric", 
                    0x0070: "Flashing Black & Electric", 
                    0x0074: "Flashing Black & Electric", 
                    0x0078: "Flashing Black & Electric", 
                    0x007C: "Brief Blue", 
                    0x0080: "Nothing", 
                    0x0084: "Nothing", 
                    0x0088: "Nothing", 
                    0x008C: "Darkness (Shortest)", 
                    0x0090: "Darkness (Shorter)", 
                    0x0094: "Darkness (Longer)", 
                    0x0098: "Darkness (Longest)", 
                    0x009C: "Dark Red", 
                    0x00A0: "Dark Red (Longer)", 
                    0x00A4: "Pink", 
                    0x00A8: "Pink (Longer)", 
                    0x00AC: "Black Tint", 
                    0x00B0: "Brief Red", 
                    0x00B4: "Flashing Yellow", 
                    0x00BC: "Flashing Yellow (Glows)", 
                    0x00C0: "Yellow Fade", 
                    0x00C4: "Orange (Long)", 
                    0x00C8: "Flashing Bluegreen", 
                    0x00CC: "Brief Yellow", 
                    0x00D0: "Brief White", 
                    0x00D4: "Flashing White w/ Lens Flare", 
                    0x00D8: "Flashing White w/ Lens Flare", 
                    0x00DC: "Brief Yellow", 
                    0x00E0: "Breif Yellow & Orange", 
                    0x00E4: "White with Cloud Above", 
                    0x00E8: "White with Cloud Around", 
                    0x00EC: "Flashing w/ Much Lens Flare", 
                    0x00F0: "Flashing White (Slow)", 
                    0x00F4: "Flashing White (Slow)", 
                    0x00F8: "Flashing White (Faster)",
                    0x00FC: "Dark Red (Gets Brighter Over Time)",  
                    0x0100: "Flashing Dark Red", 
                    0x0104: "White w/ Electric", 
                    0x0108: "Nothing", 
                    0x010C: "Flashing Electric", 
                    0x0110: "Fast Flashing White w/ Electric", 
                    0x0114: "Flashing Blue w/ Electric w/ Lens Flare", 
                    0x0118: "Fast Flashing White", 
                    0x011C: "Fire Glow from Behind", 
                    0x0120: "Fast Flashing Yellow", 
                    0x0124: "Purple Glow from Front", 
                    0x0128: "Brief Teal", 
                    0x012C: "Flashing Bluegreen w/ Electric at Feet", 
                    0x0130: "Flashing Green w/ Lens Flare", 
                    0x0134: "Full Black", 
                    0x0138: "Brief Dark Red",
                    0x013C: "Very Brief Light Blue",  
                    0x0140: "Whiter Over Time", 
                    0x0144: "White Fade", 
                    0x0148: "Flashing Blue Glow from Front", 
                    0x014C: "Brief Red/Orange", 
                    0x0150: "Greener Over Time", 
                    0x0154: "Fast Flashing Orange",
                    0x0158: "Fast Flashing White", 
                    0x015C: "Fast Flashing White", 
                    0x0160: "Brief Green", 
                    0x0164: "Flashing w/ Lens Flare & Stars", 
                    0x0168: "Flashing w/ More Lens Flare & Stars",
                    0x016C: "Pink Glow from Front",
                    0x0170: "Flashing White w/ Darkness on Left Hand",
                    0x0174: "Flashing White w/ Darkness on Right Hand",
                    0x0178: "Flashing Purple/Pink",
                    0x017C: "Brief Blue",
                    0x0180: "Faint Pink Glow from Behind",
                    0x0184: "Flashing White and Pink",
                    0x0188: "Brief Full White",
                    0x018C: "Brief White then Faint Blue",
                    0x0190: "Faint Red",
                    0x0194: "Full Black Fade",
                    0x0198: "Black",
                    0x019C: "Nothing",
                    0x01A0: "Red/Orange Over Time",
                    0x01A4: "Dark Red",
                    0x01A8: "Flashing Red and White with Cloud (Long)",
                    0x01AC: "Flashing White w/ Stars and Lens Flare (Long)",
                    0x01B0: "Sparkles",
                    0x01B4: "Flashing Red and Yellow w/ Lens Flare",
                    0x01B8: "Nothing",
                    0x01BC: "Very Brief White",
                    0x01C0: "Orange w/ Firey Glow from Front",
                    0x01C4: "Green Glow from Front to Back",
                    0x01C8: "Red",
                    0x01CC: "Blue",
                    0x01D0: "Green",
                    0x01D4: "White",
                    0x01D8: "Flashing White and Pink w/ Smoke on Ground",
                    0x01DC: "Flashing Yellow",
                    0x01E0: "Brief White",
                    0x01E4: "Brief White w/ Stars",
                    0x01E8: "Flashing Dark Red",
                    0x01EC: "Nothing",
                    0x01F0: "Nothing",
                    0x01F4: "Nothing",
                    0x01F8: "Nothing",
                    0x01FC: "Nothing" })

class Aura():
    def __init__(self, data, offset):
        self.offset = offset
        self.data = data

    @property
    def id(self): #b1 and b2 xxxxxxxI IIIIIIII xxxxxxxx xxxxxxxx
        return AURAS[get_value(self.data, 15, 9)]

    @id.setter
    def id(self, aura):
        id = Aura.AURAS[aura]
        self.data = set_value(self.data, 15, 9, id)

    def __str__(self):
        string = "Aura Event at offset " + str(self.offset) + " with command: " + hex(self.data[0])
        string += " The Aura type is: " + self.id
        return string